### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by sibero80** [billchurch/bhyve-mqtt#1]
Hello Bill, I'm a home automation enthuiast looking to monitor home water usage.
The Orbit bhyve seems a good and mature hardware but so far I have not found a manufacturer that provides an api to integrate with applications like Home Assistant.

What kind of methods, features, actions, readings does this "api" provide?

**Comment by billchurch** [comment]
This won’t work for your main water meter, it’s for irrigation. It does has some flow values exposed but I don’t have equipment that measures flow so I can’t comment on if it actually works. This is still a work in progress, I haven’t had time yet to work out control, but I can see status.
