### ISSUE TITLE
On/off working?

### ISSUE THREAD

**Issue by rocket59** [billchurch/bhyve-mqtt#10]
Sorry to post here directly but the discussion on the hass.io forums has moved in a different direction. I just wanted to ask before I picked up a b-hyve, does the mqtt command to start/stop watering now work? (ie bhyve/device/{deviceID}/zone/{num}/set). 

I'm planning to have scheduling done via node-red so basic on/off is all I need! Thanks for getting all this working, it's a pity Orbit doesn't recognise the value of opening up their API.

**Comment by jimtng** [comment]
Yes it works for me. I can turn on/off the watering using bhyve/device/{deviceID}/zone/{num}/set

**Comment by rocket59** [comment]
Brilliant, thanks!
