### ISSUE TITLE
I've got some API parts implemented if you want to check my stuff

### ISSUE THREAD

**Issue by killermonk** [billchurch/bhyve-mqtt#14]
I did a bunch of reverse engineering of the orbit API last year. If it's helpful, you can find my code here: https://github.com/blacksmithlabs/orbit-bhyve-remote

I'm not doing anything fancy like publishing to mqtt, but I've got the websocket stuff working and communication.

Wasn't sure of any other way to message you with the details, if you wanted the reference.

**Comment by dankerk** [comment]
Nice! I'm going to buy a couple of these bhyve things and see if I can add some features here or in a fork. Let's hope they don't start restricting their api's anytime soon.

**Comment by billchurch** [comment]
Looks good, checking it out, thanks.
