### ISSUE TITLE
Orbit Error: Error: timeout of 1000ms exceeded

### ISSUE THREAD

**Issue by jim77** [billchurch/bhyve-mqtt#2]
Thanks for creating this project! I have an Orbit wifi hub and two tap/faucet "timers", so I am very much interested in this project. I use OpenHAB as my automation platform.

I cloned your project and tried it out, however I received the following error:

> 2019-05-03T11:30:13.497Z - mqtt connected
> Orbit Error: Error: timeout of 1000ms exceeded

When I tried it again subsequently, I got this error:

> 2019-05-03T11:33:48.172Z - mqtt connected
> Orbit Error: Error: Request failed with status code 400

**Comment by jim77** [comment]
OK upon further investigation, the following line in .env-sample needs to be changed

ORBIT_USER => ORBIT_EMAIL

**Comment by billchurch** [comment]
Thanks @jim77 for bringing this up, fixed.
