### ISSUE TITLE
Issue 01T07:35:59.170Z - Orbit Error: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Array

### ISSUE THREAD

**Issue by Sunny99999999** [billchurch/bhyve-mqtt#23]
01T07:35:59.170Z - Orbit Error: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Array

Coming from Bhyve.Api 
Any solution  ?

**Comment by sirkingchase** [comment]
I was able to fix this by changing line 106 in app.js from `let deviceStatus = []` to `let deviceStatus = ''`
