### ISSUE TITLE
mqtt message for bhyve/deviceid/details seems to be wrong

### ISSUE THREAD

**Issue by jim77** [billchurch/bhyve-mqtt#3]
The published mqtt message for bhyve/deviceid/details contains the details for all devices. I believe it should just publish the details pertaining to that particular deviceid. This just requires one change in app.js line 86
Change from:

>       if (MCLIENT_ONLINE) mClient.publish(`bhyve/${deviceId}/details`, JSON.stringify(data))

to

>       if (MCLIENT_ONLINE) mClient.publish(`bhyve/${deviceId}/details`, JSON.stringify(data[prop]))

**Comment by billchurch** [comment]
Thanks for this, hard to test that without having a second unit... Although now it seems obvious. :)

Let me know if this resolves your issue.

**Comment by jim77** [comment]
Your latest commit fixed the bug. It's also nice that you added the ability to trigger the zones now. My immediate need for now is just to monitor the battery level using openhab and alert me when it's low. I'm running your app on start up now.
