### ISSUE TITLE
Make bhyve/deviceid/details a retained message

### ISSUE THREAD

**Issue by jim77** [billchurch/bhyve-mqtt#4]
I received the battery status in openhab upon receiving the mqtt topic "bhyve/deviceid/details". This works well when I started bhyve-mqtt after openhab. However when I restarted openhab, this status is missing. Making it retained would solve this issue nicely. 

Here's what I did to line 87 in app.js:

>         mClient.publish(`bhyve/${deviceId}/details`, JSON.stringify(data[prop]), { retain: true })

**Comment by billchurch** [comment]
Check it out, should do what you want. Also added the ability to manually control a zone, see the readme

**Comment by jim77** [comment]
I noticed your latest addition to control a zone. I also noticed that it's set to 10 seconds. I was going to make some suggestions on that. My initial idea is /bhyve/deviceid/zoneid/set 0-N with 0 = OFF and N = the number of seconds, or ON = default to 10 seconds.

**Comment by jim77** [comment]
Great work! Thanks for also updating the set options allowing us to specify the time.

**Comment by jim77** [comment]
BTW I haven't yet delved into using this topic yet, but I'm guessing that this would also benefit from "retained"

> bhyve/{deviceID}/zone/{num}

**Comment by billchurch** [comment]
Yes, it could stand to be retained also. I think I might make this an option. I didn’t want it to be stale, then again does it matter? Probably not.

**Comment by jim77** [comment]
I see a problem here. When changing the zone programming via the app, bhyve-mqtt will receive events / messages from websocket. So potentially the bhyve/deviceid/details and bhyve/deviceid/zone/num data can become invalid should changes be made after the initial run.

So for bhyve-mqtt present a dependable message for the two topics above the easiest would be to call oClient.devices() again, thus triggering the publishing of those topics to mqtt.

It would also be handy to provide a way to trigger oClient.devices() via mqtt

If you view that it's not very efficient to re-request the entire thing over again, perhaps a query about a specific device (pertaining to the websocket update message) can be made.

A separate suggestion if I may: make the connection to the mqtt broker more resilient. Inside handleClientError and also within mClient.on('offline'), set a retry timer to try to reconnect, rather than exiting the process.

**Comment by billchurch** [comment]
Yes, plenty of room for improvement for sure. Will add more to this when I get a moment. Thanks for the suggestions and testing!

**Comment by billchurch** [comment]
@jim77 also, the client will automatically reconnect if there is a disconnection, this is part of the MQTT module.
