### ISSUE TITLE
MQTT Topic to Refresh device details

### ISSUE THREAD

**Issue by billchurch** [billchurch/bhyve-mqtt#5]
MQTT topic that may be published which will trigger either all devices or a single device to refresh it's detail.

@jim77 any thoughts here?

**Comment by billchurch** [comment]
Maybe re-work the device topic to have `bhyve/device/{deviceID}` vs `bhyve/{deviceID}`

topic suggestions:

`bhyve/device/refresh`
`bhyve/device/{deviceID}/refresh`

**Comment by jim77** [comment]
Great update. I have now scheduled openhab to request an update every X hours. My current goal is just to get an up to date battery level. Unfortunately the batteries only last for about 3 months or less using NiMH rechargeable batteries (Eneloop 2000mAH or so), so I need to keep on top of it. It's the only downside to the orbit bhyve system so far.

Currently I am using bhyve/device/refresh to refresh all. Easier than refreshing each and every device. I'm sure someone will eventually come up with a need to refresh just one device / zone etc :) 

bhyve/device/{deviceID} is a good idea, and so is bhyve/device/{deviceID}/zone/{zoneID} as per your latest commit. It is a lot more readable.
